INSERT INTO roles(role_name) VALUES('ROLE_EMPLOYEE');
INSERT INTO roles(role_name) VALUES('ROLE_DOCTOR');
INSERT INTO roles(role_name) VALUES('ROLE_ADMIN');
INSERT INTO roles(role_name) VALUES('ROLE_SUPER_ADMIN');